// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	dashboardv1alpha1 "github.com/toddtreece/kubernetes-list-tests/informer/pkg/apis/dashboard/v1alpha1"
	versioned "github.com/toddtreece/kubernetes-list-tests/informer/pkg/client/clientset/versioned"
	internalinterfaces "github.com/toddtreece/kubernetes-list-tests/informer/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/toddtreece/kubernetes-list-tests/informer/pkg/client/listers/dashboard/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DashboardInformer provides access to a shared informer and lister for
// Dashboards.
type DashboardInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.DashboardLister
}

type dashboardInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDashboardInformer constructs a new informer for Dashboard type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDashboardInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDashboardInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDashboardInformer constructs a new informer for Dashboard type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDashboardInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DashboardV1alpha1().Dashboards(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DashboardV1alpha1().Dashboards(namespace).Watch(context.TODO(), options)
			},
		},
		&dashboardv1alpha1.Dashboard{},
		resyncPeriod,
		indexers,
	)
}

func (f *dashboardInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDashboardInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *dashboardInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&dashboardv1alpha1.Dashboard{}, f.defaultInformer)
}

func (f *dashboardInformer) Lister() v1alpha1.DashboardLister {
	return v1alpha1.NewDashboardLister(f.Informer().GetIndexer())
}
