// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1alpha1 "github.com/toddtreece/kubernetes-list-tests/informer/pkg/apis/dashboard/v1alpha1"
	dashboardv1alpha1 "github.com/toddtreece/kubernetes-list-tests/informer/pkg/client/applyconfiguration/dashboard/v1alpha1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=dashboard, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("Dashboard"):
		return &dashboardv1alpha1.DashboardApplyConfiguration{}

	}
	return nil
}
